{{ $imageTag := "harbor.front.kjuulh.io/library/${DRONE_REPO_NAME}"  }}

type: docker
kind: pipeline
name: "drone-dagger-test"

steps:
  - name: "build"
    image: harbor.front.kjuulh.io/docker-proxy/library/docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_BUILDKIT: 1
    commands:
      - "sleep 5"
      - apk add git
      - mkdir -p tmp/dagger-go
      - git clone "https://git.front.kjuulh.io/kjuulh/dagger-go.git" tmp/dagger-go
      - docker build -t dagger-go-builder:${DRONE_COMMIT} -f tmp/dagger-go/Dockerfile .
      - 'docker run -v /var/run/docker.sock:/var/run/docker.sock dagger-go-builder:${DRONE_COMMIT} ./dagger-go build "{{ or .input.imageTag $imageTag }}"'

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}
